[build]
  publish = "dist"
  command = "pnpm run prod || ( npm install pnpm && pnpm run prod )"
  NODE_VERSION = "18.12.0"

[dev]
  autoLaunch = false
  command = "pnpm run build"
  publish = "dist"
  port = 5173
  targetPort = 8080
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' plausible.io https://api.netlify.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; object-src 'none'; script-src 'self' 'unsafe-eval' 'unsafe-inline' plausible.io; worker-src 'self' blob:; connect-src plausible.io;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"